title: Narrow Way Church
name: Narrow Way Church
description: >-
  For the gate is small and the way is narrow that leads to life…. Matthew 7:14
baseurl: ""
url: "https://narrowwaychurch.github.io"

author: Matthew E. Denson
email: matthew@densons.org
facebook_username: Narrow Way Church

# plugins:
#   - jekyll-feed
permalink: /blog/:categories/:year/:month/:day/:title.html

markdown: kramdown

css: inline
sass:
  style: compressed


# Defaults

# Enable is_post test for posts
# Enable is_page test for pages
# Enable is_home test for home page
# Use {% if page.is_post %} etc.
defaults:
  -
    scope:
      path: ""
      layout: home
    values:
      is_home: true
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true
  -
    scope:
      path: ""
      type: pages
    values:
      is_page: true

exclude:
  - Gemfile
  - Gemfile.lock
  - docker
  - Makefile
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

