services:
  nginx:
    image: nginx:latest
    container_name: '${COMPOSE_PROJECT_NAME}_nginx'
    ports:
      - 7080:80
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ../_site:/var/www/html
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"

  jekyllproc:
    image: jekyll/jekyll:4
    container_name: '${COMPOSE_PROJECT_NAME}_jekyll'
    volumes:
      - ..:/srv/jekyll
      - ../vendor/bundle:/usr/local/bundle

